Tying to get rid of sudo

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,59 @@
-language: haskell
+sudo: false
+  # The initial part of this script was inspired by https://github.com/emwap/plugins-multistage/blob/master/.travis.yml
+language: c
 
-sudo: false  # This is required to make use of container based infrastructure
+cache:
+  directories:
+    - .cabal-sandbox
 
-env:
-  - GHCVER=7.8.3
-  - GHCVER=7.10.1
+matrix:
+  include:
+    - env: CABALVER=1.18 GHCVER=7.6.3
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.6.3]}}
+    - env: CABALVER=1.18 GHCVER=7.8.4
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.5,alex-3.1.4]}}
+    - env: CABALVER=1.22 GHCVER=7.10.1
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.22,ghc-7.10.1,happy-1.19.5,alex-3.1.4]}}
+    - env: CABALVER=head GHCVER=head
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.4]}}
+
+  allow_failures:
+    - env: CABALVER=head GHCVER=head
 
 before_install:
-  # (The following is copied from https://github.com/ekmett/lens )
-  # If $GHCVER is the one travis has, don't bother reinstalling it.
-  # We can also have faster builds by installing some libraries with
-  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
-  # with cabal-1.18.
-  - |
-    if [ $GHCVER = `ghc --numeric-version` ]; then
-      # Try installing some of the build-deps with apt-get for speed.
-      travis/cabal-apt-install --enable-tests $MODE
-      export CABAL=cabal
-    else
-      # Install the GHC we want from hvr's PPA
-      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-      travis_retry sudo apt-get update
-      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
-      export CABAL=cabal-1.18
-      export PATH=/opt/ghc/$GHCVER/bin:$PATH
-    fi
-  # Uncomment whenever hackage is down.
-  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
-  - $CABAL update
-  #####
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+  - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
+  - uname -a
 
   # The following needs to be teaked some more:
-  - sudo apt-get install unixodbc-dev
   - pwd
   - cd ..
   - git clone git://github.com/AmpersandTarski/ampersand-models.git ampersand-models
   - ls
   - cd ampersand
 
+install:
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - ghc --info
+ - travis_retry cabal update
+ - cabal sandbox init
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
+
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
+script:
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build -j2  # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal sandbox init --sandbox=../.cabal-sandbox && cabal install -j2 --force-reinstalls "$SRC_TGZ")
 
 after_script:
   - cat dist/test/*.log
